// <auto-generated />
namespace SoporteEnLinea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Uriel26072018StatusField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Uriel26072018StatusField));
        
        string IMigrationMetadata.Id
        {
            get { return "201807261423070_Uriel-26072018-StatusField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
